spring:
  datasource:
    url: jdbc:mysql://localhost:3306/boutique_hotel
    username: SET_ME
    password: SET_ME
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true